version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    environment:
      - REACT_APP_MONGO_URI=$REACT_APP_MONGO_URI
      - BACKEND_DOCKER_PORT=$BACKEND_DOCKER_PORT
      - QPLAY_GMAIL_ADRESS=$QPLAY_GMAIL_ADRESS
      - QPLAY_GMAIL_PASSWORD=$QPLAY_GMAIL_PASSWORD
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID
      - PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET
    stdin_open: true
    tty: true

  frontend:
    depends_on:
      - backend
    build: ./frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $VITE_LOCAL_PORT:$VITE_DOCKER_PORT
    environment:
      - BACKEND_NAME=app
      - VITE_BACKEND_LOCAL_PORT=$BACKEND_LOCAL_PORT
      - VITE_DOCKER_PORT=$VITE_DOCKER_PORT
    stdin_open: true
    tty: true